version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "04:00"
    timezone: Europe/Stockholm
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 20
  labels:
  - Lights On
