language: go

go:
 - "1.13.x"

install:
 - git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
 - GO111MODULE=off go get github.com/mattn/goveralls
 - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.20.0

script:
  - golangci-lint run ./...
  - go test ./... -coverprofile coverage.out -covermode count -coverpkg ./...

after_script:
  - goveralls -v -coverprofile coverage.out -service=travis-pro
