language: go

go:
 - "1.10.x"

before_install:
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/golang/dep/cmd/dep

install:
  - dep ensure

script:
  - go test ./... -coverprofile coverage.out -covermode count -coverpkg ./...
  - go vet -v ./...
  - golint -set_exit_status $(go list ./...)

after_script:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
